
- name: Install Redis Repo files
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: Enable Redis 6.2
  ansible.builtin.dnf:
    name: '@redis:remi-6.2'
    state: present

- name: Inastall redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Listen address of redis
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting redis
  ansible.builtin.systemd:
    state: restarted
    name: redis
    enabled: true

