#print_head "Create Roboshop user"
#id roboshop &>>${log_file}
#if [ "$?" -ne 0 ]; then
#useradd roboshop
#fi
#status_check $?
#print_head "Create application directory"
#if [ ! -d /app ]; then
#mkdir /app
#fi
#status_check $?
#print_head "Delete Old contents"
#rm -rf /app/* &>>${log_file}
#status_check $?
#print_head "Downloading app contents"
#curl -L -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>${log_file}
#status_check $?
#cd /app
#
#print_head "Extracting app contents"
#unzip /tmp/${component}.zip &>>${log_file}
#status_check $?

- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: delete old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory


- name: Download and Extract {{ component }} content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/${{ component }}.zip
    dest: /app
    remote_src: yes


